# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

toBinary <- function(n, k) {
    .Call('_DAGselection_toBinary', PACKAGE = 'DAGselection', n, k)
}

Tode <- function(s) {
    .Call('_DAGselection_Tode', PACKAGE = 'DAGselection', s)
}

selectdata_prelim <- function(df, indicator, m) {
    .Call('_DAGselection_selectdata_prelim', PACKAGE = 'DAGselection', df, indicator, m)
}

comparison_bps <- function(df, num_p) {
    .Call('_DAGselection_comparison_bps', PACKAGE = 'DAGselection', df, num_p)
}

get_best_parents <- function(x, C, all_names) {
    .Call('_DAGselection_get_best_parents', PACKAGE = 'DAGselection', x, C, all_names)
}

sinks <- function(all_names) {
    .Call('_DAGselection_sinks', PACKAGE = 'DAGselection', all_names)
}

